### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by muzakryder2** [CodemonChallenger/github-crash#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #b48e4c;
}
```
